name: Simple Db Tests

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test
      env:
        CI: true